# Generated by Django 3.2.7 on 2022-03-11 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCard2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('বিসিজি', models.TextField(blank=True, default='বিসিজি', null=True)),
                ('date_bcg1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_bcg2', models.CharField(blank=True, max_length=500, null=True)),
                ('bcg', models.IntegerField(blank=True, null=True)),
                ('পেন্টা', models.TextField(blank=True, default='পেন্টা (ডিপিটি, হেপ-বি, হিব)', null=True)),
                ('date_penta1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_penta2', models.CharField(blank=True, max_length=500, null=True)),
                ('date_penta3', models.CharField(blank=True, max_length=500, null=True)),
                ('penta', models.IntegerField(blank=True, null=True)),
                ('ওপিভি', models.TextField(blank=True, default='ওপিভি', null=True)),
                ('date_opv1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_opv2', models.CharField(blank=True, max_length=500, null=True)),
                ('date_opv3', models.CharField(blank=True, max_length=500, null=True)),
                ('opv', models.IntegerField(blank=True, null=True)),
                ('পিসিভি', models.TextField(blank=True, default='পিসিভি', null=True)),
                ('date_pcv1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_pcv2', models.CharField(blank=True, max_length=500, null=True)),
                ('date_pcv3', models.CharField(blank=True, max_length=500, null=True)),
                ('pcv', models.IntegerField(blank=True, null=True)),
                ('আইপিভি', models.TextField(blank=True, default='আইপিভি', null=True)),
                ('date_ipv1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_ipv2', models.CharField(blank=True, max_length=500, null=True)),
                ('ipv', models.IntegerField(blank=True, null=True)),
                ('এমআর', models.TextField(blank=True, default='এমআর ', null=True)),
                ('date_mr1', models.CharField(blank=True, max_length=500, null=True)),
                ('date_mr2', models.CharField(blank=True, max_length=500, null=True)),
                ('mr', models.IntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_assistant', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose1', models.TextField(blank=True, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('dose2', models.TextField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('dose3', models.TextField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('dose4', models.TextField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('dose5', models.TextField(blank=True, null=True)),
                ('date5', models.DateField(blank=True, null=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
