# Generated by Django 3.2.6 on 2021-08-15 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose1', models.TextField(blank=True, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('dose2', models.TextField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('dose3', models.TextField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('dose4', models.TextField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('dose5', models.TextField(blank=True, null=True)),
                ('date5', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
