# Generated by Django 3.2.6 on 2021-08-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hs',
            new_name='is_ha',
        ),
    ]
