# Generated by Django 3.2.6 on 2021-08-08 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyAttachedToHealthAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('baby', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby_user', to=settings.AUTH_USER_MODEL)),
                ('ha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_iser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
