# Generated by Django 3.2.6 on 2021-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_babyattachedtohealthassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
