# Generated by Django 3.2.6 on 2021-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baby_attached',
            field=models.BooleanField(default=False),
        ),
    ]
