# Generated by Django 3.2.6 on 2021-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_baby_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
