# Generated by Django 3.2.6 on 2021-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zilla',
            field=models.CharField(blank=True, choices=[('Dhaka-ঢাকা', 'Dhaka-ঢাকা'), ('Jessore – যশোর', 'Jessore – যশোর'), ('Dinajpur - দিনাজপুর', 'Dinajpur - দিনাজপুর'), ('Comilla – কুমিল্লা', 'Comilla – কুমিল্লা'), ('Faridpur – ফরিদপুর', 'Faridpur – ফরিদপুর'), ('Bogra – বগুড়া', 'Bogra – বগুড়া'), ('Pabna – পাবনা', 'Pabna – পাবনা'), ('Kushtia – কুষ্টিয়া', 'Kushtia – কুষ্টিয়া'), ('Noakhali - নোয়াখালী', 'Noakhali - নোয়াখালী')], max_length=30, null=True),
        ),
    ]
