# Generated by Django 3.2.6 on 2021-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_zilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
