# Generated by Django 3.2.6 on 2021-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_sub_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
