# Generated by Django 3.2.6 on 2021-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthcertificateNo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB+', 'AB+'), ('A-', 'A-'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='divisions',
            field=models.CharField(blank=True, choices=[('Chittagong-চট্টগ্রাম', 'Chittagong-চট্টগ্রাম'), ('Dhaka-ঢাকা', 'Dhaka-ঢাকা'), ('Rajshahi-রাজশাহী', 'Rajshahi-রাজশাহী'), ('Sylhet-সিলেট', 'Sylhet-সিলেট'), ('Mymensingh-ময়মনসিংহ', 'Mymensingh-ময়মনসিংহ'), ('Barisal-বরিশাল', 'Barisal-বরিশাল'), ('Rangpur-রংপুর', 'Rangpur-রংপুর'), ('Khulna-খুলনা', 'Khulna-খুলনা')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fatherName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='get_vaccine_from',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='holdingNo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='motherName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationNo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_block',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='union',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='word_no',
            field=models.CharField(blank=True, choices=[('word-1', 'word-1'), ('word-2', 'word-2'), ('word-3', 'word-3'), ('word-4', 'word-4'), ('word-5', 'word-5'), ('word-6', 'word-6'), ('word-7', 'word-7'), ('word-8', 'word-8'), ('word-9', 'word-9'), ('word-10', 'word-10'), ('word-11', 'word-11'), ('word-12', 'word-12'), ('word-13', 'word-13'), ('word-14', 'word-14'), ('word-15', 'word-15'), ('word-16', 'word-16'), ('word-17', 'word-17'), ('word-18', 'word-18'), ('word-19', 'word-19'), ('word-20', 'word-20')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zilla',
            field=models.CharField(blank=True, choices=[('Dhaka-ঢাকা', 'Dhaka-ঢাকা'), ('Jessore – যশোর', 'Jessore – যশোর'), ('Dinajpur - দিনাজপুর', 'Dinajpur - দিনাজপুর'), ('Comilla – কুমিল্লা', 'Comilla – কুমিল্লা'), ('Faridpur – ফরিদপুর', 'Faridpur – ফরিদপুর'), ('Bogra – বগুড়া', 'Bogra – বগুড়া'), ('Pabna – পাবনা', 'Pabna – পাবনা'), ('Kushtia – কুষ্টিয়া', 'Kushtia – কুষ্টিয়া'), ('Noakhali - নোয়াখালী', 'Noakhali - নোয়াখালী')], max_length=1000, null=True),
        ),
    ]
